# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc876ff11883d593aca01a104e527568ed579eda82cadc21b6ba83de8c1317e7d29c1fd60780907a7604369aa566a4c433f790e1f2b63e0fc4bc5a6adddd4113

test:
  secret_key_base: 1c02a5927e90629ce8e63b52ba6044db0c6fba8eb8d5217b3459d79f86ca32ef803955377e170c0dc88792f10008404a9bdefdf500b9fcb43bfb2c6be7dce22f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
